version: 2

sources:
  - name: googles_analytics_4
    schema: google_analytics_4
    tables:
      - name: events_20210131
      
  - name: google_sheets
    schema: google_sheets
    tables:
      - name: account_manager_region_mapping

  - name: dataset_fil_rouge
    schema: dataset_fil_rouge
    tables:
      - name: feedback
      - name: payment
      - name: product
      - name: order
      - name: order_item
      - name: seller
      - name: user

  - name: dataset_session_3
    schema: dataset_session_3
    tables:
      - name: listening_data
      - name: songs

  - name: airbnb
    schema: airbnb
    tables:
      - name: listings

  - name: local_bike
    schema: local_bike
    tables:
      - name: brands
      - name: categories
      - name: customers
      - name: order_items
      - name: orders
      - name: products
      - name: staffs
      - name: stocks
      - name: stores